### ISSUE TITLE
Siji Fonts Verify Fails

### ISSUE THREAD

**Issue by tbsteinb** [szorfein/ninjatools#1]
When I go to emerge media-fonts/siji (either version) portage fails due to a verification failure. For both versions it expects a size of 47298 and gets a size of 47293.

**Comment by szorfein** [comment]
so yes, thx for issue, full message here:
```
2018-01-30 14:24:26 (32,6 KB/s) - ‘/usr/portage/distfiles/siji-1.0.zip’ saved [47293/47293]

!!! Fetched file: siji-1.0.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      47293
!!! Expected: 47298
Refetching... File renamed to '/usr/portage/distfiles/siji-1.0.zip._checksum_failure_.ls2nu_t4'

!!! Couldn't download 'siji-1.0.zip'. Aborting.
```
The project don't publish releases, so signature change sometime...I will make a siji-9999.ebuild today :).
